<?php

$filePath1 = 'util/Misc.php';
$filePath2 = '../util/Misc.php';

if (file_exists($filePath1)) {
    require_once $filePath1;
} elseif (file_exists($filePath2)) {
    require_once $filePath2;
} else {
    die("Error: File does not exist in both directories.");
}

enum Office: string
{
    case SANGGUNIANG_PANLUNGSOD = 'Sangguniang Panlungsod';
    case PARKS_PLAYGROUND = 'PARKS & PLAYGROUND';
    case OFFICE_OF_THE_CITY_VICE_MAYOR = 'OFFICE OF THE CITY VICE-MAYOR';
    case OFFICE_OF_THE_CITY_MAYOR = 'OFFICE OF THE CITY MAYOR';
    case OFFICE_OF_THE_CITY_CIVIL_REGISTRAR = 'OFFICE OF THE CITY CIVIL REGISTRAR (OCCR)';
    case OFFICE_OF_THE_CITY_ASSESSORS = 'OFFICE OF THE CITY ASSESSORS';
    case OFFICE_OF_THE_CITY_ADMINISTRATOR = 'OFFICE OF THE CITY ADMINISTRATOR';
    case OFFICE_OF_THE_CITY_ACCOUNTANT = 'OFFICE OF THE CITY ACCOUNTANT';
    case OFFICE_OF_THE_BUILDING_OFFICIAL = 'OFFICE OF THE BUILDING OFFICIAL (OBO)';
    case OFFICE_OF_CITY_BUDGET = 'OFFICE OF CITY BUDGET';
    case MANAGEMENT_INFORMATION_COMPUTER_SERVICES = 'MANAGEMENT INFORMATION & COMPUTER SERVICES (MICS)';
    case LOCAL_SCHOOL_BOARD = 'LOCAL SCHOOL BOARD(LSB)';
    case INVITATION_TO_BID = 'Invitation to BID (Notice of Auction Sale)';
    case INTERNAL_AUDIT_SERVICE_OFFICE = 'INTERNAL AUDIT SERVICE OFFICE (IASO)';
    case HUMAN_RESOURCE_DEVELOPMENT_OFFICE = 'HUMAN RESOURCE AND DEVELOPMENT OFFICE (HRDO)';
    case DEPARTMENT_OF_VETERINARY_MEDICINE_FISHERIES = 'DEPARTMENT OF VETERINARY MEDICINE & FISHERIES (DVMF)';
    case DEPARTMENT_OF_SOCIAL_WELFARE_SERVICES = 'DEPARTMENT OF SOCIAL WELFARE AND SERVICES (DSWS)';
    case DEPARTMENT_OF_PUBLIC_SERVICES = 'DEPARTMENT OF PUBLIC SERVICES (DPS)';
    case DEPARTMENT_OF_MANPOWER_DEVELOPMENT_PLACEMENT = 'DEPARTMENT OF MANPOWER DEVELOPMENT AND PLACEMENT (DMDP)';
    case DEPARTMENT_OF_GENERAL_SERVICES = 'DEPARTMENT OF GENERAL SERVICES (DGS)';
    case DEPARTMENT_OF_ENGINEERING_PUBLIC_WORKS = 'DEPARTMENT OF ENGINEERING & PUBLIC WORKS (DEPW)';
    case CONTACT_CENTER_NG_BAYAN_PARTNER_RECOGNITION_PROGRAM = 'Contact Center ng Bayan Partner Recognition Program';
    case CITY_TREASURERS_OFFICE = 'CITY TREASURER’S OFFICE (CTO)';
    case CITY_PLANNING_DEVELOPMENT_OFFICE = 'CITY PLANNING DEVELOPMENT OFFICE (CPDO)';
    case CITY_LEGAL_OFFICE = 'CITY LEGAL OFFICE';
    case CITY_HEALTH_DEPARTMENT = 'CITY HEALTH DEPARTMENT (CHD)';
    case CITY_AGRICULTURE_DEPARTMENT = 'CITY AGRICULTURE DEPARTMENT (CAD)';
    case CEBU_CITY_TRANSPORTATION_OFFICE = 'CEBU CITY TRANSPORTATION OFFICE (CCTO)';
    case CEBU_CITY_RESOURCE_MANAGEMENT_DEVELOPMENT_CENTER = 'CEBU CITY RESOURCE MANAGEMENT AND DEVELOPMENT CENTER (CREMDEC)';
    case CEBU_CITY_MEDICAL_CENTER = 'CEBU CITY MEDICAL CENTER (CCMC)';

    public static function all(): array
    {
        return Misc::displayEnums(self::cases());
    }
}
